Repository Pronto-AG/Pronto-MIA-App, pull requests merged in 2021-06, with the labels that each got.

#72 Enhancement/user crud
  pronto_mia/lib/core/factories/analyzed_error_factory.dart
  pronto_mia/lib/core/factories/error_message_factory.dart
  pronto_mia/lib/core/models/access_control_list.dart
  pronto_mia/lib/core/models/department.dart
  pronto_mia/lib/core/models/deployment_plan.dart
  pronto_mia/lib/core/models/profiles.dart
  pronto_mia/lib/core/models/user.dart
  pronto_mia/lib/core/queries/user_queries.dart
  pronto_mia/lib/core/services/jwt_token_service.dart
  pronto_mia/lib/core/services/user_service.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.form.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_viewmodel.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_view.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_viewmodel.dart
Labels: enhancement, waiting for review

#76 Enhancement/acl
  pronto_mia/lib/core/models/access_control_list.dart
  pronto_mia/lib/core/models/profiles.dart
  pronto_mia/lib/core/models/user.dart
  pronto_mia/lib/core/queries/user_queries.dart
  pronto_mia/lib/core/services/user_service.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu.dart
  pronto_mia/lib/ui/shared/theme.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_viewmodel.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_view.dart
Labels: enhancement, waiting for review

#78 Bug/android build
  .github/workflows/main.yml
  pronto_mia/android/app/build.gradle
Labels: bug, waiting for review

#79 V3 dev
  pronto_mia/lib/core/factories/analyzed_error_factory.dart
  pronto_mia/lib/core/factories/error_message_factory.dart
  pronto_mia/lib/core/models/access_control_list.dart
  pronto_mia/lib/core/models/department.dart
  pronto_mia/lib/core/models/deployment_plan.dart
  pronto_mia/lib/core/models/profiles.dart
  pronto_mia/lib/core/models/user.dart
  pronto_mia/lib/core/queries/user_queries.dart
  pronto_mia/lib/core/services/jwt_token_service.dart
  pronto_mia/lib/core/services/user_service.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu.dart
  pronto_mia/lib/ui/shared/theme.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.form.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_viewmodel.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_view.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_viewmodel.dart
Labels: enhancement

#80 Enhancement/department crud
  pronto_mia/lib/app/service_locator.dart
  pronto_mia/lib/core/models/access_control_list.dart
  pronto_mia/lib/core/models/deployment_plan.dart
  pronto_mia/lib/core/queries/department_queries.dart
  pronto_mia/lib/core/queries/deployment_plan_queries.dart
  pronto_mia/lib/core/queries/user_queries.dart
  pronto_mia/lib/core/services/department_service.dart
  pronto_mia/lib/core/services/deployment_plan_service.dart
  pronto_mia/lib/core/services/user_service.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu.dart
  pronto_mia/lib/ui/views/department/edit/department_edit_view.dart
  pronto_mia/lib/ui/views/department/edit/department_edit_view.form.dart
  pronto_mia/lib/ui/views/department/edit/department_edit_viewmodel.dart
  pronto_mia/lib/ui/views/department/overview/department_overview_view.dart
  pronto_mia/lib/ui/views/department/overview/department_overview_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.form.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.form.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_viewmodel.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_view.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_viewmodel.dart
Labels: enhancement, waiting for review

#82 Enhancement/acl restrictions
  pronto_mia/lib/core/models/profiles.dart
  pronto_mia/lib/core/queries/user_queries.dart
  pronto_mia/lib/core/services/user_service.dart
  pronto_mia/lib/ui/components/custom_app_bar.dart
  pronto_mia/lib/ui/components/navigation_layout.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu.dart
  pronto_mia/lib/ui/views/department/overview/department_overview_view.dart
  pronto_mia/lib/ui/views/department/overview/department_overview_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_viewmodel.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_view.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_viewmodel.dart
Labels: enhancement, waiting for review

#84 Enhancement/password reset
  pronto_mia/lib/core/factories/analyzed_error_factory.dart
  pronto_mia/lib/core/queries/authentication_queries.dart
  pronto_mia/lib/core/services/authentication_service.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu_viewmodel.dart
  pronto_mia/lib/ui/views/department/edit/department_edit_view.dart
  pronto_mia/lib/ui/views/department/edit/department_edit_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_viewmodel.dart
  pronto_mia/lib/ui/views/settings/settings_view.dart
  pronto_mia/lib/ui/views/settings/settings_view.form.dart
  pronto_mia/lib/ui/views/settings/settings_viewmodel.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_viewmodel.dart
Labels: enhancement, waiting for review

#85 acl profiles
  pronto_mia/lib/core/models/profiles.dart
Labels: bug, enhancement, waiting for review

#86 Enhancement/error handling
  pronto_mia/lib/core/factories/analyzed_error_factory.dart
  pronto_mia/lib/core/factories/error_message_factory.dart
  pronto_mia/lib/core/models/analyzed_error.dart
Labels: enhancement

#87 Fix department update
  pronto_mia/lib/core/queries/department_queries.dart
Labels: bug

#88 Prepare release 0.3.0 for iOS
  CHANGELOG.md
  assets/store/ios/ipad_12.9/department_overview.png
  assets/store/ios/ipad_12.9/deployment_plan_create.png
  assets/store/ios/ipad_12.9/deployment_plan_edit.png
  assets/store/ios/ipad_12.9/deployment_plan_management.png
  assets/store/ios/ipad_12.9/deployment_plan_overview.png
  assets/store/ios/ipad_12.9/deployment_plan_publish.png
  assets/store/ios/ipad_12.9/user_edit.png
  assets/store/ios/ipad_12.9/user_overview.png
  assets/store/ios/ipad_9.7/department_overview.png
  assets/store/ios/ipad_9.7/deployment_plan_create.png
  assets/store/ios/ipad_9.7/deployment_plan_edit.png
  assets/store/ios/ipad_9.7/deployment_plan_management.png
  assets/store/ios/ipad_9.7/deployment_plan_overview.png
  assets/store/ios/ipad_9.7/deployment_plan_publish.png
  assets/store/ios/ipad_9.7/user_edit.png
  assets/store/ios/ipad_9.7/user_overview.png
  assets/store/ios/iphone/department_overview.png
  assets/store/ios/iphone/deployment_plan_create.png
  assets/store/ios/iphone/deployment_plan_edit.png
  assets/store/ios/iphone/deployment_plan_management.png
  assets/store/ios/iphone/deployment_plan_overview.png
  assets/store/ios/iphone/deployment_plan_publish.png
  assets/store/ios/iphone/login.png
  assets/store/ios/iphone/user_edit.png
  assets/store/ios/iphone/user_overview.png
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/pubspec.yaml
Labels: enhancement, waiting for review

#90 Add 5.5 inch screenshots
  assets/store/ios/ipad/12.9_inch/department_overview.png
  assets/store/ios/ipad/12.9_inch/deployment_plan_edit.png
  assets/store/ios/ipad/12.9_inch/deployment_plan_management.png
  assets/store/ios/ipad/12.9_inch/deployment_plan_overview.png
  assets/store/ios/ipad/12.9_inch/deployment_plan_publish.png
  assets/store/ios/ipad/12.9_inch/login.png
  assets/store/ios/ipad/12.9_inch/user_edit.png
  assets/store/ios/ipad/12.9_inch/user_overview.png
  assets/store/ios/ipad/9.7_inch/department_overview.png
  assets/store/ios/ipad/9.7_inch/deployment_plan_edit.png
  assets/store/ios/ipad/9.7_inch/deployment_plan_management.png
  assets/store/ios/ipad/9.7_inch/deployment_plan_overview.png
  assets/store/ios/ipad/9.7_inch/deployment_plan_publish.png
  assets/store/ios/ipad/9.7_inch/login.png
  assets/store/ios/ipad/9.7_inch/user_edit.png
  assets/store/ios/ipad/9.7_inch/user_overview.png
  assets/store/ios/iphone/5.5_inch/department_overview.png
  assets/store/ios/iphone/5.5_inch/deployment_plan_edit.png
  assets/store/ios/iphone/5.5_inch/deployment_plan_management.png
  assets/store/ios/iphone/5.5_inch/deployment_plan_overview.png
  assets/store/ios/iphone/5.5_inch/deployment_plan_publish.png
  assets/store/ios/iphone/5.5_inch/login.png
  assets/store/ios/iphone/5.5_inch/user_edit.png
  assets/store/ios/iphone/5.5_inch/user_overview.png
  assets/store/ios/iphone/6.5_inch/department_overview.png
  assets/store/ios/iphone/6.5_inch/deployment_plan_edit.png
  assets/store/ios/iphone/6.5_inch/deployment_plan_management.png
  assets/store/ios/iphone/6.5_inch/deployment_plan_overview.png
  assets/store/ios/iphone/6.5_inch/deployment_plan_publish.png
  assets/store/ios/iphone/6.5_inch/login.png
  assets/store/ios/iphone/6.5_inch/user_edit.png
  assets/store/ios/iphone/6.5_inch/user_overview.png
Labels: enhancement

#91 Chore/testing
  .github/workflows/main.yml
  pronto_mia/analysis_options.yaml
  pronto_mia/lib/core/services/configuration_service.dart
  pronto_mia/lib/core/services/deployment_plan_service.dart
  pronto_mia/lib/core/services/graphql_service.dart
  pronto_mia/lib/core/services/jwt_token_service.dart
  pronto_mia/lib/core/services/pdf_service.dart
  pronto_mia/lib/core/services/push_notification_service.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu_viewmodel.dart
  pronto_mia/lib/ui/views/department/overview/department_overview_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/lib/ui/views/login/login_viewmodel.dart
  pronto_mia/lib/ui/views/pdf/pdf_viewmodel.dart
  pronto_mia/lib/ui/views/startup/startup_viewmodel.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_viewmodel.dart
  pronto_mia/pubspec.lock
  pronto_mia/pubspec.yaml
  pronto_mia/test/services/authentication_service_test.dart
  pronto_mia/test/services/department_service_test.dart
  pronto_mia/test/services/deployment_plan_service_test.dart
  pronto_mia/test/services/error_service_test.dart
  pronto_mia/test/services/graphql_service_test.dart
  pronto_mia/test/services/jwt_token_service_test.dart
  pronto_mia/test/services/pdf_service_test.dart
  pronto_mia/test/services/push_notification_service_test.dart
  pronto_mia/test/services/user_service_test.dart
  pronto_mia/test/setup/test_helpers.dart
  pronto_mia/test/setup/test_helpers.mocks.dart
  pronto_mia/test/viewmodels/department_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/department_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/deployment_plan_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/deployment_plan_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/login_viewmodel_test.dart
  pronto_mia/test/viewmodels/pdf_viewmodel_test.dart
  pronto_mia/test/viewmodels/settings_viewmodel_test.dart
  pronto_mia/test/viewmodels/startup_viewmodel_test.dart
  pronto_mia/test/viewmodels/user_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/user_overview_viewmodel_test.dart
Labels: enhancement

#92 Update version index
  pronto_mia/pubspec.yaml
Labels: enhancement

#94 Update app_settings_prod.json
  pronto_mia/assets/cfg/app_settings_dev.json
  pronto_mia/assets/cfg/app_settings_prod.json
Labels: enhancement

#96 Fix ci
  .github/workflows/main.yml
Labels: bug
