Repository Pronto-AG/Pronto-MIA-App, pull requests merged in 2021-05, with the labels that each got.

#42 Enhancement/fcm permission request
  pronto_mia/lib/core/services/authentication_service.dart
  pronto_mia/lib/core/services/push_notification_service.dart
  pronto_mia/lib/main.dart
  pronto_mia/lib/ui/components/form_layout.dart
  pronto_mia/lib/ui/views/startup/startup_viewmodel.dart
Labels: enhancement

#45 Enhancement/desktop layout
  pronto_mia/lib/app/service_locator.dart
  pronto_mia/lib/app/theme.dart
  pronto_mia/lib/main.dart
  pronto_mia/lib/ui/components/custom_app_bar.dart
  pronto_mia/lib/ui/components/data_view_layout.dart
  pronto_mia/lib/ui/components/form_layout.dart
  pronto_mia/lib/ui/components/navigation_layout.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu_viewmodel.dart
  pronto_mia/lib/ui/shared/custom_colors.dart
  pronto_mia/lib/ui/shared/custom_dialogs.dart
  pronto_mia/lib/ui/shared/theme.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/lib/ui/views/login/login_view.dart
  pronto_mia/lib/ui/views/login/login_viewmodel.dart
  pronto_mia/lib/ui/views/pdf/pdf_view.dart
  pronto_mia/lib/ui/views/startup/startup_view.dart
  pronto_mia/pubspec.lock
  pronto_mia/pubspec.yaml
Labels: enhancement, waiting for review

#49 #48 Adjust readme and build gradle
  README.md
  pronto_mia/android/app/build.gradle
  pronto_mia/pubspec.yaml
Labels: enhancement

#50 Enhancement/pdf web
  pronto_mia/lib/app/app.router.dart
  pronto_mia/lib/core/models/simple_file.dart
  pronto_mia/lib/core/services/deployment_plan_service.dart
  pronto_mia/lib/core/services/pdf_service.dart
  pronto_mia/lib/ui/components/data_view_layout.dart
  pronto_mia/lib/ui/components/navigation_layout.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.form.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/lib/ui/views/pdf/pdf_view.dart
  pronto_mia/lib/ui/views/pdf/pdf_viewmodel.dart
  pronto_mia/pubspec.lock
  pronto_mia/pubspec.yaml
  pronto_mia/web/index.html
Labels: enhancement, waiting for review

#54 Enhancement/push
  assets/icon_notification.svg
  pronto_mia/android/app/src/main/AndroidManifest.xml
  pronto_mia/android/app/src/main/kotlin/ch/prontoag/mia/MainActivity.kt
  pronto_mia/android/app/src/main/res/drawable/ic_icon_notification.xml
  pronto_mia/lib/core/queries/deployment_plan_queries.dart
  pronto_mia/lib/core/services/deployment_plan_service.dart
  pronto_mia/lib/core/services/push_notification_service.dart
  pronto_mia/lib/main.dart
  pronto_mia/lib/ui/components/deployment_plan_notification.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/web/firebase-messaging-sw.js
Labels: enhancement

#59 Enhancement/cache manager options
  pronto_mia/lib/core/services/pdf_service.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.form.dart
  pronto_mia/lib/ui/views/login/login_view.dart
  pronto_mia/lib/ui/views/login/login_view.form.dart
  pronto_mia/pubspec.lock
  pronto_mia/pubspec.yaml
Labels: enhancement

#55 #41 Add publish to gui
  pronto_mia/lib/core/models/deployment_plan.dart
  pronto_mia/lib/core/models/simple_file.dart
  pronto_mia/lib/core/models/user.dart
  pronto_mia/lib/core/queries/deployment_plan_queries.dart
  pronto_mia/lib/core/services/deployment_plan_service.dart
  pronto_mia/lib/core/services/pdf_service.dart
  pronto_mia/lib/core/services/push_notification_service.dart
  pronto_mia/lib/core/services/user_service.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
Labels: enhancement

#56 Enhancement/gui improvements
  pronto_mia/lib/app/app.dart
  pronto_mia/lib/app/app.router.dart
  pronto_mia/lib/core/services/deployment_plan_service.dart
  pronto_mia/lib/core/services/pdf_service.dart
  pronto_mia/lib/main.dart
  pronto_mia/lib/ui/components/custom_app_bar.dart
  pronto_mia/lib/ui/components/destructive_button/destructive_button.dart
  pronto_mia/lib/ui/components/destructive_button/destructive_button_viewmodel.dart
  pronto_mia/lib/ui/components/form_layout.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu_viewmodel.dart
  pronto_mia/lib/ui/shared/theme.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/lib/ui/views/login/login_view.dart
  pronto_mia/lib/ui/views/login/login_viewmodel.dart
  pronto_mia/lib/ui/views/startup/startup_viewmodel.dart
  pronto_mia/pubspec.lock
  pronto_mia/pubspec.yaml
Labels: bug, enhancement, waiting for review

#61 #51 Fix error state recovery
  pronto_mia/lib/ui/views/login/login_viewmodel.dart
Labels: bug, waiting for review

#63 Fix timezone filter
  pronto_mia/lib/core/services/deployment_plan_service.dart
  pronto_mia/lib/core/services/graphql_service.dart
Labels: bug, waiting for review

#64 Bug/authentication
  pronto_mia/lib/app/service_locator.dart
  pronto_mia/lib/core/factories/analyzed_error_factory.dart
  pronto_mia/lib/core/factories/error_message_factory.dart
  pronto_mia/lib/core/models/analyzed_error.dart
  pronto_mia/lib/core/services/error_service.dart
  pronto_mia/lib/ui/components/navigation_menu/navigation_menu_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/edit/deployment_plan_edit_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/lib/ui/views/login/login_viewmodel.dart
  pronto_mia/lib/ui/views/pdf/pdf_viewmodel.dart
  pronto_mia/lib/ui/views/startup/startup_viewmodel.dart
  pronto_mia/web/icons/Icon-192.png
  pronto_mia/web/icons/Icon-512.png
  pronto_mia/web/manifest.json
Labels: bug, enhancement

#65 Implement ios specific configuration
  pronto_mia/.gitignore
  pronto_mia/ios/Flutter/Debug.xcconfig
  pronto_mia/ios/Flutter/Release.xcconfig
  pronto_mia/ios/Podfile
  pronto_mia/ios/Podfile.lock
  pronto_mia/ios/Runner.xcodeproj/project.pbxproj
  pronto_mia/ios/Runner.xcworkspace/contents.xcworkspacedata
  pronto_mia/ios/Runner/Info.plist
  pronto_mia/ios/Runner/Runner.entitlements
Labels: enhancement, waiting for review

#66 Enhancement/ios
  CHANGELOG.md
  README.md
  pronto_mia/ios/Runner.xcodeproj/project.pbxproj
  pronto_mia/ios/Runner/Info.plist
  pronto_mia/pubspec.yaml
Labels: enhancement, waiting for review

#67 Add assets for store
  assets/store/android/introduction_graphic.png
  assets/store/android/phone/deployment_plan_edit_overview.png
  assets/store/android/phone/deployment_plan_overview.png
  assets/store/android/phone/edit_deployment_plan.png
  assets/store/android/phone/login.png
  assets/store/android/phone/new_deployment_plan.png
  assets/store/android/phone/publish_deployment_plan.png
  assets/store/android/phone/published_deploymen_plan.png
  assets/store/android/symbol.png
  assets/store/android/tablet_10/deployment_plan_edit_overview.png
  assets/store/android/tablet_10/deployment_plan_overview.png
  assets/store/android/tablet_10/edit_deployment_plan.png
  assets/store/android/tablet_10/login.png
  assets/store/android/tablet_10/new_deployment_plan.png
  assets/store/android/tablet_10/publish_deployment_plan.png
  assets/store/android/tablet_10/published_deploymen_plan.png
  assets/store/android/tablet_7/deployment_plan_edit_overview.png
  assets/store/android/tablet_7/deployment_plan_overview.png
  assets/store/android/tablet_7/edit_deployment_plan.png
  assets/store/android/tablet_7/login.png
  assets/store/android/tablet_7/new_deployment_plan.png
  assets/store/android/tablet_7/publish_deployment_plan.png
  assets/store/android/tablet_7/published_deploymen_plan.png
Labels: documentation

#75 Enhancement/ios release
  .gitignore
  assets/store/ios/ipad_12.9/deployment_plan_create.png
  assets/store/ios/ipad_12.9/deployment_plan_edit.png
  assets/store/ios/ipad_12.9/deployment_plan_management.png
  assets/store/ios/ipad_12.9/deployment_plan_overview.png
  assets/store/ios/ipad_12.9/deployment_plan_publish.png
  assets/store/ios/ipad_12.9/login.png
  assets/store/ios/ipad_9.7/deployment_plan_create.png
  assets/store/ios/ipad_9.7/deployment_plan_edit.png
  assets/store/ios/ipad_9.7/deployment_plan_management.png
  assets/store/ios/ipad_9.7/deployment_plan_overview.png
  assets/store/ios/ipad_9.7/deployment_plan_publish.png
  assets/store/ios/ipad_9.7/login.png
  assets/store/ios/iphone/deployment_plan_create.png
  assets/store/ios/iphone/deployment_plan_edit.png
  assets/store/ios/iphone/deployment_plan_management.png
  assets/store/ios/iphone/deployment_plan_overview.png
  assets/store/ios/iphone/deployment_plan_publish.png
  assets/store/ios/iphone/login.png
  pronto_mia/assets/cfg/app_settings_dev.json
  pronto_mia/assets/cfg/app_settings_prod.json
  pronto_mia/ios/Flutter/AppFrameworkInfo.plist
  pronto_mia/ios/Runner.xcodeproj/project.pbxproj
  pronto_mia/ios/Runner/Info.plist
  pronto_mia/lib/generated_plugin_registrant.dart
  pronto_mia/pubspec.yaml
Labels: enhancement, waiting for review
