Repository Pronto-AG/Pronto-MIA-App, pull requests merged in 2021-12, with the labels that each got.

#123 Issue120
  .github/workflows/main.yml
  .gitignore
  pronto_mia/assets/cfg/app_settings_mailer.json
  pronto_mia/assets/cfg/mailer_credentials.json
  pronto_mia/lib/app/service_locator.dart
  pronto_mia/lib/core/services/configuration_service.dart
  pronto_mia/lib/core/services/external_news_service.dart
  pronto_mia/lib/core/services/inquiry_service.dart
  pronto_mia/lib/ui/components/form_layout.dart
  pronto_mia/lib/ui/views/department/overview/department_overview_viewmodel.dart
  pronto_mia/lib/ui/views/external_news/edit/external_news_edit_viewmodel.dart
  pronto_mia/lib/ui/views/external_news/overview/external_news_overview_view.dart
  pronto_mia/lib/ui/views/external_news/overview/external_news_overview_viewmodel.dart
  pronto_mia/lib/ui/views/inquiry/inquiry_view.dart
  pronto_mia/lib/ui/views/inquiry/inquiry_viewmodel.dart
  pronto_mia/lib/ui/views/login/login_view.dart
  pronto_mia/lib/ui/views/login/login_viewmodel.dart
  pronto_mia/pubspec.yaml
  pronto_mia/test/setup/test_helpers.dart
  pronto_mia/test/setup/test_helpers.mocks.dart
  pronto_mia/test/viewmodels/department_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/external_news_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/external_news_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/external_news_view_viewmodel_test.dart
  pronto_mia/test/viewmodels/inquiry_view_viewmodel_test.dart
  pronto_mia/test/viewmodels/login_viewmodel_test.dart
  pronto_mia/test/viewmodels/user_overview_viewmodel_test.dart
Labels: enhancement

#126 Issue104
  pronto_mia/lib/core/services/deployment_plan_service.dart
  pronto_mia/lib/ui/views/appointment/view/appointment_view.dart
Labels: enhancement

#133 #127 Test Coverage
  pronto_mia/ios/Podfile.lock
  pronto_mia/lib/core/services/educational_content_service.dart
  pronto_mia/lib/core/services/internal_news_service.dart
  pronto_mia/lib/ui/views/appointment/edit/appointment_edit_viewmodel.dart
  pronto_mia/lib/ui/views/educational_content/edit/educational_content_edit_viewmodel.dart
  pronto_mia/lib/ui/views/educational_content/overview/educational_content_overview_viewmodel.dart
  pronto_mia/lib/ui/views/internal_news/edit/internal_news_edit_viewmodel.dart
  pronto_mia/lib/ui/views/internal_news/overview/internal_news_overview_viewmodel.dart
  pronto_mia/test/services/appointment_service_test.dart
  pronto_mia/test/services/educational_content_service_test.dart
  pronto_mia/test/services/external_news_service_test.dart
  pronto_mia/test/services/internal_news_service_test.dart
  pronto_mia/test/setup/test_helpers.dart
  pronto_mia/test/setup/test_helpers.mocks.dart
  pronto_mia/test/viewmodels/appointment_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/appointment_view_viewmodel_test.dart
  pronto_mia/test/viewmodels/educational_content_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/educational_content_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/educational_content_view_viewmodel_test.dart
  pronto_mia/test/viewmodels/internal_news_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/internal_news_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/internal_news_view_viewmodel_test.dart
Labels: chore

#135 Issue134
  .github/workflows/main.yml
  pronto_mia/ios/Podfile.lock
  pronto_mia/lib/core/models/profiles.dart
  pronto_mia/lib/core/queries/appointment_queries.dart
  pronto_mia/lib/core/services/appointment_service.dart
  pronto_mia/lib/core/services/educational_content_service.dart
  pronto_mia/lib/core/services/external_news_service.dart
  pronto_mia/lib/core/services/internal_news_service.dart
  pronto_mia/lib/core/services/push_notification_service.dart
  pronto_mia/lib/ui/views/appointment/edit/appointment_edit_view.dart
  pronto_mia/lib/ui/views/appointment/edit/appointment_edit_view.form.dart
  pronto_mia/lib/ui/views/appointment/view/appointment_view.dart
  pronto_mia/lib/ui/views/appointment/view/appointment_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/lib/ui/views/educational_content/edit/educational_content_edit_view.dart
  pronto_mia/lib/ui/views/educational_content/edit/educational_content_edit_viewmodel.dart
  pronto_mia/lib/ui/views/educational_content/overview/educational_content_overview_view.dart
  pronto_mia/lib/ui/views/educational_content/overview/educational_content_overview_viewmodel.dart
  pronto_mia/lib/ui/views/external_news/edit/external_news_edit_view.dart
  pronto_mia/lib/ui/views/external_news/edit/external_news_edit_viewmodel.dart
  pronto_mia/lib/ui/views/external_news/overview/external_news_overview_viewmodel.dart
  pronto_mia/lib/ui/views/internal_news/edit/internal_news_edit_view.dart
  pronto_mia/lib/ui/views/internal_news/edit/internal_news_edit_viewmodel.dart
  pronto_mia/lib/ui/views/internal_news/overview/internal_news_overview_viewmodel.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_view.dart
  pronto_mia/lib/ui/views/user/edit/user_edit_viewmodel.dart
  pronto_mia/test/services/appointment_service_test.dart
  pronto_mia/test/services/department_service_test.dart
  pronto_mia/test/services/deployment_plan_service_test.dart
  pronto_mia/test/services/educational_content_service_test.dart
  pronto_mia/test/services/external_news_service_test.dart
  pronto_mia/test/services/image_service_test.dart
  pronto_mia/test/services/internal_news_service_test.dart
  pronto_mia/test/services/user_service_test.dart
  pronto_mia/test/setup/test_helpers.dart
  pronto_mia/test/setup/test_helpers.mocks.dart
  pronto_mia/test/viewmodels/appointment_view_viewmodel_test.dart
  pronto_mia/test/viewmodels/educational_content_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/external_news_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/internal_news_overview_viewmodel_test.dart
Labels: bug, chore

#138 Issue136
  .github/workflows/main.yml
  CHANGELOG.md
  pronto_mia/lib/ui/views/appointment/edit/appointment_edit_view.dart
  pronto_mia/lib/ui/views/appointment/view/appointment_view.dart
  pronto_mia/lib/ui/views/department/overview/department_overview_viewmodel.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_viewmodel.dart
  pronto_mia/lib/ui/views/settings/overview/settings_overview_viewmodel.dart
  pronto_mia/lib/ui/views/user/overview/user_overview_viewmodel.dart
  pronto_mia/test/services/educational_content_service_test.dart
  pronto_mia/test/viewmodels/department_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/department_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/deployment_plan_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/deployment_plan_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/educational_content_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/educational_content_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/external_news_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/internal_news_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/settings_overview_viewmodel_test.dart
  pronto_mia/test/viewmodels/user_edit_viewmodel_test.dart
  pronto_mia/test/viewmodels/user_overview_viewmodel_test.dart
Labels: chore

#142 Deployment v1.0
  CHANGELOG.md
  pronto_mia/ios/Podfile.lock
  pronto_mia/ios/Runner.xcodeproj/project.pbxproj
  pronto_mia/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  pronto_mia/lib/core/models/profiles.dart
  pronto_mia/lib/core/services/educational_content_service.dart
  pronto_mia/lib/core/services/external_news_service.dart
  pronto_mia/lib/core/services/internal_news_service.dart
  pronto_mia/lib/ui/components/data_view_layout.dart
  pronto_mia/lib/ui/components/navigation_layout.dart
  pronto_mia/lib/ui/shared/custom_colors.dart
  pronto_mia/lib/ui/views/appointment/edit/appointment_edit_view.dart
  pronto_mia/lib/ui/views/deployment_plan/overview/deployment_plan_overview_view.dart
  pronto_mia/lib/ui/views/educational_content/overview/educational_content_overview_view.dart
  pronto_mia/lib/ui/views/educational_content/view/educational_content_view.dart
  pronto_mia/lib/ui/views/external_news/overview/external_news_overview_view.dart
  pronto_mia/lib/ui/views/external_news/view/external_news_view.dart
  pronto_mia/lib/ui/views/internal_news/overview/internal_news_overview_view.dart
  pronto_mia/lib/ui/views/internal_news/view/internal_news_view.dart
  pronto_mia/lib/ui/views/settings/overview/settings_overview_view.dart
  pronto_mia/lib/ui/views/settings/view/settings_view.dart
  pronto_mia/pubspec.lock
  pronto_mia/pubspec.yaml
Labels: chore
